[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.release-ffi]
inherits = "release"
panic = "unwind"

[workspace]
members = [
	"crates/opforge-types",
	"crates/opforge-vm",
	"crates/opforge-package",
	"crates/opforge-registry",
	"crates/opforge-ffi",
	"crates/opforge-core",
	"crates/opforge-asm",
	"crates/opforge-families",
	"crates/opforge-engine",
	"crates/opforge-formatter",
	"crates/opforge-lsp",
	"crates/opforge-lib",
	"crates/opforge-cli",
	"crates/opforge-cli-core",
]
resolver = "2"
