; Generated by build_native_packages; data only, offsets relative to Catalog.
Catalog
	.long CatalogEnd-Catalog
	.long CatalogEntries-Catalog
	.long CatalogAliases-Catalog
	.word 16
	.word 40
CatalogEntries
	.long CatalogKey0-Catalog
	.word 19
	.word 1
	.long CatalogCpu0-Catalog
	.word 6
	.word 11
	.long CatalogDialect0-Catalog
	.long 0
	.long 0
	.long CatalogKey1-Catalog
	.word 18
	.word 1
	.long CatalogCpu1-Catalog
	.word 5
	.word 11
	.long CatalogDialect1-Catalog
	.long 0
	.long 0
	.long CatalogKey2-Catalog
	.word 18
	.word 1
	.long CatalogCpu2-Catalog
	.word 5
	.word 11
	.long CatalogDialect2-Catalog
	.long 0
	.long 0
	.long CatalogKey3-Catalog
	.word 15
	.word 1
	.long CatalogCpu3-Catalog
	.word 4
	.word 9
	.long CatalogDialect3-Catalog
	.long 0
	.long 0
	.long CatalogKey4-Catalog
	.word 11
	.word 0
	.long CatalogCpu4-Catalog
	.word 4
	.word 5
	.long CatalogDialect4-Catalog
	.long 0
	.long 0
	.long CatalogKey5-Catalog
	.word 20
	.word 1
	.long CatalogCpu5-Catalog
	.word 6
	.word 12
	.long CatalogDialect5-Catalog
	.long 0
	.long 0
	.long CatalogKey6-Catalog
	.word 18
	.word 1
	.long CatalogCpu6-Catalog
	.word 5
	.word 11
	.long CatalogDialect6-Catalog
	.long 0
	.long 0
	.long CatalogKey7-Catalog
	.word 19
	.word 1
	.long CatalogCpu7-Catalog
	.word 6
	.word 11
	.long CatalogDialect7-Catalog
	.long 0
	.long 0
	.long CatalogKey8-Catalog
	.word 19
	.word 1
	.long CatalogCpu8-Catalog
	.word 6
	.word 11
	.long CatalogDialect8-Catalog
	.long 0
	.long 0
	.long CatalogKey9-Catalog
	.word 19
	.word 1
	.long CatalogCpu9-Catalog
	.word 6
	.word 11
	.long CatalogDialect9-Catalog
	.long 0
	.long 0
	.long CatalogKey10-Catalog
	.word 19
	.word 1
	.long CatalogCpu10-Catalog
	.word 6
	.word 11
	.long CatalogDialect10-Catalog
	.long 0
	.long 0
	.long CatalogKey11-Catalog
	.word 19
	.word 1
	.long CatalogCpu11-Catalog
	.word 6
	.word 11
	.long CatalogDialect11-Catalog
	.long 0
	.long 0
	.long CatalogKey12-Catalog
	.word 19
	.word 1
	.long CatalogCpu12-Catalog
	.word 6
	.word 11
	.long CatalogDialect12-Catalog
	.long 0
	.long 0
	.long CatalogKey13-Catalog
	.word 19
	.word 1
	.long CatalogCpu13-Catalog
	.word 5
	.word 12
	.long CatalogDialect13-Catalog
	.long 0
	.long 0
	.long CatalogKey14-Catalog
	.word 14
	.word 0
	.long CatalogCpu14-Catalog
	.word 3
	.word 9
	.long CatalogDialect14-Catalog
	.long 0
	.long 0
	.long CatalogKey15-Catalog
	.word 10
	.word 1
	.long CatalogCpu15-Catalog
	.word 3
	.word 5
	.long CatalogDialect15-Catalog
	.long 0
	.long 0
CatalogAliases
	.long CatalogAliasName0-Catalog
	.word 4
	.word 6
	.long CatalogAliasCpu0-Catalog
	.long CatalogAliasName1-Catalog
	.word 6
	.word 6
	.long CatalogAliasCpu1-Catalog
	.long CatalogAliasName2-Catalog
	.word 4
	.word 6
	.long CatalogAliasCpu2-Catalog
	.long CatalogAliasName3-Catalog
	.word 4
	.word 5
	.long CatalogAliasCpu3-Catalog
	.long CatalogAliasName4-Catalog
	.word 5
	.word 5
	.long CatalogAliasCpu4-Catalog
	.long CatalogAliasName5-Catalog
	.word 5
	.word 5
	.long CatalogAliasCpu5-Catalog
	.long CatalogAliasName6-Catalog
	.word 6
	.word 5
	.long CatalogAliasCpu6-Catalog
	.long CatalogAliasName7-Catalog
	.word 5
	.word 6
	.long CatalogAliasCpu7-Catalog
	.long CatalogAliasName8-Catalog
	.word 5
	.word 6
	.long CatalogAliasCpu8-Catalog
	.long CatalogAliasName9-Catalog
	.word 5
	.word 6
	.long CatalogAliasCpu9-Catalog
	.long CatalogAliasName10-Catalog
	.word 5
	.word 6
	.long CatalogAliasCpu10-Catalog
	.long CatalogAliasName11-Catalog
	.word 5
	.word 6
	.long CatalogAliasCpu11-Catalog
	.long CatalogAliasName12-Catalog
	.word 5
	.word 6
	.long CatalogAliasCpu12-Catalog
	.long CatalogAliasName13-Catalog
	.word 4
	.word 5
	.long CatalogAliasCpu13-Catalog
	.long CatalogAliasName14-Catalog
	.word 4
	.word 4
	.long CatalogAliasCpu14-Catalog
	.long CatalogAliasName15-Catalog
	.word 4
	.word 4
	.long CatalogAliasCpu15-Catalog
	.long CatalogAliasName16-Catalog
	.word 7
	.word 6
	.long CatalogAliasCpu16-Catalog
	.long CatalogAliasName17-Catalog
	.word 5
	.word 6
	.long CatalogAliasCpu17-Catalog
	.long CatalogAliasName18-Catalog
	.word 6
	.word 6
	.long CatalogAliasCpu18-Catalog
	.long CatalogAliasName19-Catalog
	.word 11
	.word 6
	.long CatalogAliasCpu19-Catalog
	.long CatalogAliasName20-Catalog
	.word 7
	.word 6
	.long CatalogAliasCpu20-Catalog
	.long CatalogAliasName21-Catalog
	.word 5
	.word 6
	.long CatalogAliasCpu21-Catalog
	.long CatalogAliasName22-Catalog
	.word 5
	.word 5
	.long CatalogAliasCpu22-Catalog
	.long CatalogAliasName23-Catalog
	.word 6
	.word 6
	.long CatalogAliasCpu23-Catalog
	.long CatalogAliasName24-Catalog
	.word 6
	.word 6
	.long CatalogAliasCpu24-Catalog
	.long CatalogAliasName25-Catalog
	.word 6
	.word 6
	.long CatalogAliasCpu25-Catalog
	.long CatalogAliasName26-Catalog
	.word 6
	.word 6
	.long CatalogAliasCpu26-Catalog
	.long CatalogAliasName27-Catalog
	.word 6
	.word 6
	.long CatalogAliasCpu27-Catalog
	.long CatalogAliasName28-Catalog
	.word 6
	.word 6
	.long CatalogAliasCpu28-Catalog
	.long CatalogAliasName29-Catalog
	.word 5
	.word 5
	.long CatalogAliasCpu29-Catalog
	.long CatalogAliasName30-Catalog
	.word 7
	.word 6
	.long CatalogAliasCpu30-Catalog
	.long CatalogAliasName31-Catalog
	.word 7
	.word 6
	.long CatalogAliasCpu31-Catalog
	.long CatalogAliasName32-Catalog
	.word 7
	.word 6
	.long CatalogAliasCpu32-Catalog
	.long CatalogAliasName33-Catalog
	.word 7
	.word 6
	.long CatalogAliasCpu33-Catalog
	.long CatalogAliasName34-Catalog
	.word 7
	.word 6
	.long CatalogAliasCpu34-Catalog
	.long CatalogAliasName35-Catalog
	.word 7
	.word 6
	.long CatalogAliasCpu35-Catalog
	.long CatalogAliasName36-Catalog
	.word 6
	.word 5
	.long CatalogAliasCpu36-Catalog
	.long CatalogAliasName37-Catalog
	.word 6
	.word 6
	.long CatalogAliasCpu37-Catalog
	.long CatalogAliasName38-Catalog
	.word 7
	.word 5
	.long CatalogAliasCpu38-Catalog
	.long CatalogAliasName39-Catalog
	.word 3
	.word 3
	.long CatalogAliasCpu39-Catalog
CatalogKey0
	.byte "45gs02--transparent",0
CatalogCpu0
	.byte "45gs02",0
CatalogDialect0
	.byte "transparent",0
CatalogKey1
	.byte "65816--transparent",0
CatalogCpu1
	.byte "65816",0
CatalogDialect1
	.byte "transparent",0
CatalogKey2
	.byte "65c02--transparent",0
CatalogCpu2
	.byte "65c02",0
CatalogDialect2
	.byte "transparent",0
CatalogKey3
	.byte "8085--intel8080",0
CatalogCpu3
	.byte "8085",0
CatalogDialect3
	.byte "intel8080",0
CatalogKey4
	.byte "8085--zilog",0
CatalogCpu4
	.byte "8085",0
CatalogDialect4
	.byte "zilog",0
CatalogKey5
	.byte "hd6309--motorola680x",0
CatalogCpu5
	.byte "hd6309",0
CatalogDialect5
	.byte "motorola680x",0
CatalogKey6
	.byte "m6502--transparent",0
CatalogCpu6
	.byte "m6502",0
CatalogDialect6
	.byte "transparent",0
CatalogKey7
	.byte "m68000--motorola68k",0
CatalogCpu7
	.byte "m68000",0
CatalogDialect7
	.byte "motorola68k",0
CatalogKey8
	.byte "m68010--motorola68k",0
CatalogCpu8
	.byte "m68010",0
CatalogDialect8
	.byte "motorola68k",0
CatalogKey9
	.byte "m68020--motorola68k",0
CatalogCpu9
	.byte "m68020",0
CatalogDialect9
	.byte "motorola68k",0
CatalogKey10
	.byte "m68030--motorola68k",0
CatalogCpu10
	.byte "m68030",0
CatalogDialect10
	.byte "motorola68k",0
CatalogKey11
	.byte "m68040--motorola68k",0
CatalogCpu11
	.byte "m68040",0
CatalogDialect11
	.byte "motorola68k",0
CatalogKey12
	.byte "m68080--motorola68k",0
CatalogCpu12
	.byte "m68080",0
CatalogDialect12
	.byte "motorola68k",0
CatalogKey13
	.byte "m6809--motorola680x",0
CatalogCpu13
	.byte "m6809",0
CatalogDialect13
	.byte "motorola680x",0
CatalogKey14
	.byte "z80--intel8080",0
CatalogCpu14
	.byte "z80",0
CatalogDialect14
	.byte "intel8080",0
CatalogKey15
	.byte "z80--zilog",0
CatalogCpu15
	.byte "z80",0
CatalogDialect15
	.byte "zilog",0
CatalogAliasName0
	.byte "4510",0
CatalogAliasCpu0
	.byte "45gs02",0
CatalogAliasName1
	.byte "45gs02",0
CatalogAliasCpu1
	.byte "45gs02",0
CatalogAliasName2
	.byte "6309",0
CatalogAliasCpu2
	.byte "hd6309",0
CatalogAliasName3
	.byte "6502",0
CatalogAliasCpu3
	.byte "m6502",0
CatalogAliasName4
	.byte "65816",0
CatalogAliasCpu4
	.byte "65816",0
CatalogAliasName5
	.byte "65c02",0
CatalogAliasCpu5
	.byte "65c02",0
CatalogAliasName6
	.byte "65c816",0
CatalogAliasCpu6
	.byte "65816",0
CatalogAliasName7
	.byte "68000",0
CatalogAliasCpu7
	.byte "m68000",0
CatalogAliasName8
	.byte "68010",0
CatalogAliasCpu8
	.byte "m68010",0
CatalogAliasName9
	.byte "68020",0
CatalogAliasCpu9
	.byte "m68020",0
CatalogAliasName10
	.byte "68030",0
CatalogAliasCpu10
	.byte "m68030",0
CatalogAliasName11
	.byte "68040",0
CatalogAliasCpu11
	.byte "m68040",0
CatalogAliasName12
	.byte "68080",0
CatalogAliasCpu12
	.byte "m68080",0
CatalogAliasName13
	.byte "6809",0
CatalogAliasCpu13
	.byte "m6809",0
CatalogAliasName14
	.byte "8080",0
CatalogAliasCpu14
	.byte "8085",0
CatalogAliasName15
	.byte "8085",0
CatalogAliasCpu15
	.byte "8085",0
CatalogAliasName16
	.byte "csg4510",0
CatalogAliasCpu16
	.byte "45gs02",0
CatalogAliasName17
	.byte "h6309",0
CatalogAliasCpu17
	.byte "hd6309",0
CatalogAliasName18
	.byte "hd6309",0
CatalogAliasCpu18
	.byte "hd6309",0
CatalogAliasName19
	.byte "hitachi6309",0
CatalogAliasCpu19
	.byte "hd6309",0
CatalogAliasName20
	.byte "m45gs02",0
CatalogAliasCpu20
	.byte "45gs02",0
CatalogAliasName21
	.byte "m6309",0
CatalogAliasCpu21
	.byte "hd6309",0
CatalogAliasName22
	.byte "m6502",0
CatalogAliasCpu22
	.byte "m6502",0
CatalogAliasName23
	.byte "m68000",0
CatalogAliasCpu23
	.byte "m68000",0
CatalogAliasName24
	.byte "m68010",0
CatalogAliasCpu24
	.byte "m68010",0
CatalogAliasName25
	.byte "m68020",0
CatalogAliasCpu25
	.byte "m68020",0
CatalogAliasName26
	.byte "m68030",0
CatalogAliasCpu26
	.byte "m68030",0
CatalogAliasName27
	.byte "m68040",0
CatalogAliasCpu27
	.byte "m68040",0
CatalogAliasName28
	.byte "m68080",0
CatalogAliasCpu28
	.byte "m68080",0
CatalogAliasName29
	.byte "m6809",0
CatalogAliasCpu29
	.byte "m6809",0
CatalogAliasName30
	.byte "mc68000",0
CatalogAliasCpu30
	.byte "m68000",0
CatalogAliasName31
	.byte "mc68010",0
CatalogAliasCpu31
	.byte "m68010",0
CatalogAliasName32
	.byte "mc68020",0
CatalogAliasCpu32
	.byte "m68020",0
CatalogAliasName33
	.byte "mc68030",0
CatalogAliasCpu33
	.byte "m68030",0
CatalogAliasName34
	.byte "mc68040",0
CatalogAliasCpu34
	.byte "m68040",0
CatalogAliasName35
	.byte "mc68080",0
CatalogAliasCpu35
	.byte "m68080",0
CatalogAliasName36
	.byte "mc6809",0
CatalogAliasCpu36
	.byte "m6809",0
CatalogAliasName37
	.byte "mega65",0
CatalogAliasCpu37
	.byte "45gs02",0
CatalogAliasName38
	.byte "w65c816",0
CatalogAliasCpu38
	.byte "65816",0
CatalogAliasName39
	.byte "z80",0
CatalogAliasCpu39
	.byte "z80",0
	.align 2
CatalogEnd
