[package]
name = "vm"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
types = { path = "../opforge-types" }
opcore = { path = "../opforge-core" }
package = { path = "../opforge-package" }
registry = { path = "../opforge-registry" }
families = { path = "../opforge-families" }
