; Native AmigaOS opForge CLI shell.
;
; This first slice mirrors the Rust CLI argument names for a strict native
; subset and provides deterministic stage stubs until parser/emitter VMs exist
; on AmigaOS.

	.module opforge.cli.constants
	.cpu 68020
	.use tkpkg.amigaos.buffers

	.pub

SYS_BASE                        = 4

PR_CLI                          = 172
PR_MSG_PORT                     = 92
PR_COS                          = 160
PR_CES                          = 224

OPEN_LIBRARY                    = -552
CLOSE_LIBRARY                   = -414
FIND_TASK                       = -294
WAIT_PORT                       = -384
GET_MSG                         = -372
REPLY_MSG                       = -378
FORBID                          = -132

OPEN                            = -30
CLOSE                           = -36
READ                            = -42
WRITE                           = -48
PUT_STR                         = -948
FPUTS                           = -342
GET_ARG_STR                     = -534

MODE_OLDFILE                    = 1005
MODE_NEWFILE                    = 1006

RETURN_OK                       = 0
RETURN_USAGE                    = 1
RETURN_FILE_FAILURE             = 1
RETURN_RUNTIME_FAILURE          = 1
RETURN_NOT_IMPLEMENTED          = 1
RETURN_WORKBENCH_UNSUPPORTED    = 31

NCLI_PARSE_OK                   = 0
NCLI_PARSE_HELP                 = 1
NCLI_PARSE_VERSION              = 2
NCLI_PARSE_USAGE                = -1
NCLI_PARSE_QUOTED               = -2
NCLI_PARSE_UNSUPPORTED          = -3
NCLI_PARSE_UNKNOWN_FLAG         = -4
NCLI_PARSE_MISSING_VALUE        = -5
NCLI_PARSE_NO_INPUT             = -6
NCLI_PARSE_HUNK_REQUIRED        = -7
NCLI_PARSE_MIXED_INPUT          = -8
NCLI_PARSE_MULTIPLE_POSITIONAL  = -9
NCLI_PARSE_MODULE_PATH_CAPACITY = -10
NCLI_PARSE_INCLUDE_PATH_CAPACITY = -11

NATIVE_OUTPUT_FORMAT_NONE       = 0
NATIVE_OUTPUT_FORMAT_BIN        = 1
NATIVE_OUTPUT_FORMAT_HUNK       = 2
NATIVE_OUTPUT_FORMAT_PRG        = 3
NATIVE_OUTPUT_FORMAT_HEX        = 4
NATIVE_OUTPUT_FORMAT_LST        = 5

PATH_BUFFER_CAPACITY            = 256
TOKEN_BUFFER_CAPACITY           = 64
SOURCE_LINE_BUFFER_CAPACITY     = 512
NATIVE_SOURCE_RECORD_CAPACITY   = 512
NATIVE_MODULE_TABLE_CAPACITY    = 16
NATIVE_IMPORT_TABLE_CAPACITY    = 32
NATIVE_MODULE_PATH_CAPACITY     = 8
NATIVE_INCLUDE_PATH_CAPACITY    = 8
NATIVE_IMPORT_SELECT_CAPACITY   = 64
NATIVE_ORDINARY_EXPORT_CAPACITY = 64
NATIVE_STATEMENT_TABLE_CAPACITY = NATIVE_SOURCE_RECORD_CAPACITY
NATIVE_LABEL_TABLE_CAPACITY     = 16
NATIVE_IMAGE_BUFFER_CAPACITY    = 4096
NATIVE_PREPROCESS_EXPANSION_DEPTH_LIMIT = 1
NATIVE_PREPROCESS_DEFINITION_CAPACITY = 8
NATIVE_PREPROCESS_BODY_LINE_CAPACITY = 8
NATIVE_PREPROCESS_MACRO_ARG_CAPACITY = 9
NATIVE_PREPROCESS_INVOCATION_DEPTH_LIMIT = 1
; Native macro storage is deliberately fixed.  These text capacities name the
; individual owners rather than implying that their buffers can be shared.
; Definition headers retain the macro name/signature in one source-line slot.
NATIVE_PREPROCESS_DEFINITION_HEADER_CAPACITY = SOURCE_LINE_BUFFER_CAPACITY
NATIVE_PREPROCESS_BODY_LINE_TEXT_CAPACITY = SOURCE_LINE_BUFFER_CAPACITY
NATIVE_PREPROCESS_INVOCATION_ARG_TEXT_CAPACITY = SOURCE_LINE_BUFFER_CAPACITY
NATIVE_PREPROCESS_INVOCATION_FULL_ARGS_CAPACITY = SOURCE_LINE_BUFFER_CAPACITY
NATIVE_PREPROCESS_INVOCATION_LABEL_CAPACITY = SOURCE_LINE_BUFFER_CAPACITY
NATIVE_PREPROCESS_SAVED_LINE_CAPACITY = SOURCE_LINE_BUFFER_CAPACITY
NATIVE_PREPROCESS_EXPANSION_LINE_CAPACITY = SOURCE_LINE_BUFFER_CAPACITY
; Structural-definition record kinds. MACRO expands with lexical scope;
; SEGMENT and STATEMENT expand inline through their dedicated matchers.
NATIVE_PREPROCESS_DEFINITION_KIND_MACRO = 0
NATIVE_PREPROCESS_DEFINITION_KIND_SEGMENT = 1
NATIVE_PREPROCESS_DEFINITION_KIND_STATEMENT = 2
NATIVE_PREPROCESS_VISIBILITY_PRIVATE = 0
NATIVE_PREPROCESS_VISIBILITY_PUBLIC = 1
NATIVE_PREPROCESS_IMPORT_BINDING_CAPACITY = NATIVE_IMPORT_SELECT_CAPACITY
NATIVE_PREPROCESS_IMPORT_BINDING_NAME_CAPACITY = SOURCE_LINE_BUFFER_CAPACITY
NATIVE_STATEMENT_OUTPUT_BYTES   = NATIVE_STATEMENT_TABLE_CAPACITY * 12
NATIVE_SOURCE_TEXT_BYTES        = NATIVE_SOURCE_RECORD_CAPACITY * SOURCE_LINE_BUFFER_CAPACITY
NATIVE_ASSEMBLY_SESSION_BYTES   = (5 * 2) + TOKEN_BUFFER_CAPACITY + (2 * 4) + (NATIVE_SOURCE_RECORD_CAPACITY * 4) + (NATIVE_SOURCE_RECORD_CAPACITY * 2) + NATIVE_SOURCE_TEXT_BYTES + (NATIVE_STATEMENT_TABLE_CAPACITY * 4) + (NATIVE_STATEMENT_TABLE_CAPACITY * 2) + (NATIVE_STATEMENT_TABLE_CAPACITY * SOURCE_LINE_BUFFER_CAPACITY) + (NATIVE_STATEMENT_TABLE_CAPACITY * 2) + (NATIVE_STATEMENT_TABLE_CAPACITY * 2) + (NATIVE_STATEMENT_TABLE_CAPACITY * 2) + (NATIVE_STATEMENT_TABLE_CAPACITY * 2) + (NATIVE_STATEMENT_TABLE_CAPACITY * 4) + NATIVE_STATEMENT_OUTPUT_BYTES + (NATIVE_STATEMENT_TABLE_CAPACITY * TOKEN_BUFFER_CAPACITY) + (NATIVE_STATEMENT_TABLE_CAPACITY * TOKEN_BUFFER_CAPACITY) + (NATIVE_STATEMENT_TABLE_CAPACITY * TOKEN_BUFFER_CAPACITY) + (NATIVE_STATEMENT_TABLE_CAPACITY * 2) + (NATIVE_STATEMENT_TABLE_CAPACITY * 4) + (NATIVE_STATEMENT_TABLE_CAPACITY * 4) + (NATIVE_STATEMENT_TABLE_CAPACITY * 4) + (NATIVE_STATEMENT_TABLE_CAPACITY * 4) + (NATIVE_STATEMENT_TABLE_CAPACITY * 4) + (NATIVE_STATEMENT_TABLE_CAPACITY * 4) + (NATIVE_STATEMENT_TABLE_CAPACITY * 4) + (NATIVE_LABEL_TABLE_CAPACITY * 4) + (NATIVE_LABEL_TABLE_CAPACITY * TOKEN_BUFFER_CAPACITY) + NATIVE_IMAGE_BUFFER_CAPACITY
PACKAGE_INPUT_PTR_V1            = buffers.LAST_ERROR_BUFFER_PTR_V1 + buffers.LAST_ERROR_BUFFER_CAPACITY
NATIVE_INCLUDE_DEPTH_LIMIT      = 1
PRVM_ROUTE_MAGIC_OPLR           = $4F504C52
PRVM_ROUTE_FRAME_SIZE           = 116
PRVM_ROUTE_ABI_VERSION_V1       = 1
PRVM_PARSER_CONTRACT_VERSION_V2 = 2
PRVM_ROUTE_RESULT_CAPACITY      = 512
PRVM_ROUTE_DIAG_CAPACITY        = 32
PRVM_ROUTE_RESUME_CAPACITY      = 40
PRVM_ROUTE_EXPR_REQUEST_SIZE    = 32
PRVM_ROUTE_EXPR_RESULT_SIZE     = 32
PRVM_ROUTE_EXPR_RESULT_CAPACITY = 16
PRVM_ROUTE_EXPR_RESULT_COUNT    = 0
PRVM_ROUTE_STEP_BUDGET          = 256
PRVM_STATUS_OK                  = 0
PRVM_STATUS_EXPR_REQUEST        = 1
PRVM_EXPR_SLOT_READY            = 1
PRVM_RESULT_RECORD_SIZE         = 32
PRVM_RESULT_RECORD_COUNT        = PRVM_ROUTE_RESULT_CAPACITY / PRVM_RESULT_RECORD_SIZE
PRVM_RESULT_LABEL_TEXT          = 2
PRVM_RESULT_MNEMONIC_TEXT       = 3
PRVM_RESULT_OPERAND_EXPR_SLOT   = 4
PRVM_RESULT_DIRECTIVE_TEXT      = 6
PRVM_RESULT_OPERAND_TEXT        = 7
NATIVE_TOKEN_RECORD_SIZE        = 20
NATIVE_EVAL_EXPR_EXTENSION_BYTES = 28
NATIVE_EVAL_EXPR_EXTENSION_PTR_V1 = buffers.LAST_ERROR_BUFFER_PTR_V1 + buffers.LAST_ERROR_BUFFER_CAPACITY - NATIVE_EVAL_EXPR_EXTENSION_BYTES
TK_KIND_IDENTIFIER              = 0
NCLI_PARSER_DIRECTIVE_NONE      = 0
NCLI_PARSER_DIRECTIVE_MODULE    = 1
NCLI_PARSER_DIRECTIVE_ENDMODULE = 2
NCLI_PARSER_DIRECTIVE_USE       = 3
NCLI_PARSER_DIRECTIVE_GENERIC   = 4

	.endmodule
