; Native opasm callback/service ABI constants.
;
; This module is intentionally data-free: it publishes the fixed frame and event
; record offsets shared by opasm-owned assembly drivers and CLI-side renderers.

	.module opasm.amigaos.callback_abi
	.cpu 68020
	.pub

OPASM_ASSEMBLE_REQ_BIN_REQUESTED_PTR = 0
OPASM_ASSEMBLE_REQ_EVENT_BUFFER_PTR = 4
OPASM_ASSEMBLE_REQ_EVENT_CAPACITY = 8
OPASM_ASSEMBLE_REQ_EVENT_COUNT_PTR = 10
OPASM_ASSEMBLE_REQ_SERVICE_FRAME_PTR = 14
OPASM_ASSEMBLE_REQ_DIAG_BUFFER_PTR = 18
OPASM_ASSEMBLE_REQ_DIAG_BUFFER_CAPACITY = 22
OPASM_ASSEMBLE_REQ_FLAGS = 24
OPASM_ASSEMBLE_REQ_BYTES = 26

OPASM_SERVICE_CONTROL_BLOCK_PTR = 0
OPASM_SERVICE_IO_BUFFER_PTR = 4
OPASM_SERVICE_IO_BUFFER_CAPACITY = 8
OPASM_SERVICE_EVAL_EXTENSION_PTR = 10
OPASM_SERVICE_EVAL_EXTENSION_BYTES = 14
; Optional architecture-neutral name resolver supplied by the embedding CLI.
; Inputs: A0/D0 token, A1/D1 active module name. Outputs: A0/D0 rewritten
; fully-qualified name and D1=0, or D1=1 when no import mapping applies.
OPASM_SERVICE_IMPORT_NAME_RESOLVER_PTR = 16
OPASM_SERVICE_BYTES = 20

OPASM_STATUS_OK = 0
OPASM_STATUS_DUPLICATE_LABEL = 1
OPASM_STATUS_IMAGE_CAPACITY = 2
OPASM_STATUS_BAD_ORG = 3
OPASM_STATUS_SERVICE_FAILURE = 4
OPASM_STATUS_EVENT_CAPACITY = 5

OPASM_EVENT_KIND = 0
OPASM_EVENT_PASS = 2
OPASM_EVENT_STMT_INDEX = 4
OPASM_EVENT_FLAGS = 6
OPASM_EVENT_TEXT_PTR = 8
OPASM_EVENT_TEXT_LEN = 12
OPASM_EVENT_AUX_PTR = 14
OPASM_EVENT_AUX_LEN = 18
OPASM_EVENT_VALUE = 20
OPASM_EVENT_STATUS = 24
OPASM_EVENT_SERVICE_ORD = 26
OPASM_EVENT_RESERVED = 28
OPASM_EVENT_BYTES = 32

OPASM_EVENT_PASS_BEGIN = 1
OPASM_EVENT_PASS_OK = 2
OPASM_EVENT_LABEL_STORED = 3
OPASM_EVENT_LABEL_DUPLICATE = 4
OPASM_EVENT_IMAGE_CAPACITY_EXCEEDED = 5
OPASM_EVENT_SELECTOR_STATUS_OK = 6
OPASM_EVENT_UNKNOWN_MNEMONIC = 7
OPASM_EVENT_UNSUPPORTED_ADDRESSING = 8
OPASM_EVENT_UNRESOLVED_LABEL = 9
OPASM_EVENT_BAD_ORG = 10
OPASM_EVENT_SERVICE_FAILURE = 11

	.endmodule
